def handle(args, agent):
    """Show available in-chat commands."""
    print()
    print("Available commands:")
    print()
    print("  /undo                     Undo the last agent commit")
    print("  /redo                     Re-apply the last undone commit")
    print("  /reasoning on|off         Toggle reasoning output (persists to roles.json)")
    print("  /reasoningEffort <value>  Set provider reasoning effort (low, medium, high, ...) or 'auto'")
    print("  /model <name>             Change the model for the current role (persists to roles.json)")
    print("  /windowSize <num>         Set context window size in tokens (persists to roles.json)")
    print("  /globalTodo on|off        Toggle shared todo lists across subagents (persists to roles.json)")
    print("  /thinkingMode <num|name>  Set thinking mode (1-5 or zen, serious, extreme, feral, insane)")
    print("  /reindex [--force]        Re-index the codebase (use --force to re-index all files)")
    print("  /health                   Generate a full code complexity report")
    print("  /skills                   List all loaded skills with summaries")
    print("  /reload-skills            Re-scan skill directories and refresh the agent's skill list")
    print("  /use <name>               Inject a skill's content into the conversation for the agent to follow")
    print("  /whitelist                Review whitelisted shell commands and optionally remove some")
    print("  /help                     Show this help message")
    print("  !<command>                Run a shell command (e.g. !ls -la)")
    print()
    print("  Ctrl+C         Go back")
    print("  Ctrl+D         Leave the chat")
    print()
    print("Press Esc followed by Enter to send message, or type 'exit' to quit")

    return ""
